const SHOP_DATA = {
  eCat: {
    id: 1,
    title: "Състезания Елит категория",
    routeName: "eCat",
    items: [
      {
        id: 18,
        name: "Държавно първенство категория Елит",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/XzcwL5s/black-shearling.png",
        price: 125,
        cat: 'e',
      },
      {
        id: 19,
        name: "Държавно отборно първенство",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
        price: 90,
        cat: 'e',
      },
      {
        id: 20,
        name: "Grey Jean Jacket",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
        price: 90,
        cat: 'e',
      },
      {
        id: 21,
        name: "Brown Shearling",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/s96FpdP/brown-shearling.png",
        price: 165,
        cat: 'e',
      },
      {
        id: 22,
        name: "Tan Trench",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
        price: 185,
        cat: 'e',
      },
    ],
  },
  aCat: {
    id: 2,
    title: "Състезания A категория",
    routeName: "aCat",
    items: [
      {
        id: 1,
        name: "Brown Brim",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        price: 25,
        cat: 'a',
      },
      {
        id: 2,
        name: "Blue Beanie",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 18,
        cat: 'a',
      },
      {
        id: 3,
        name: "Brown Cowboy",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
        price: 35,
        cat: 'a',
      },
      {
        id: 4,
        name: "Grey Brim",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
        price: 25,
        cat: 'a',
      },
      {
        id: 5,
        name: "Green Beanie",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/YTjW3vF/green-beanie.png",
        price: 18,
      },
      {
        id: 6,
        name: "Palm Tree Cap",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
        price: 14,
        cat: 'a',
      },
      {
        id: 7,
        name: "Red Beanie",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/bLB646Z/red-beanie.png",
        price: 18,
        cat: 'a',
      },
      {
        id: 8,
        name: "Wolf Cap",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/1f2nWMM/wolf-cap.png",
        price: 14,
        cat: 'a',
      },
      {
        id: 9,
        name: "Blue Snapback",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/X2VJP2W/blue-snapback.png",
        price: 16,
        cat: 'a',
      },
    ],
  },
  bCat: {
    id: 3,
    title: "Състезания Б категория",
    routeName: "bCat",
    items: [
      {
        id: 10,
        name: "Adidas NMD",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
        price: 220,
        cat: 'b',
      },
      {
        id: 11,
        name: "Adidas Yeezy",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
        price: 280,
        cat: 'b',
      },
      {
        id: 12,
        name: "Black Converse",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/bPmVXyP/black-converse.png",
        price: 110,
        cat: 'b',
      },
      {
        id: 13,
        name: "Nike White AirForce",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
        price: 160,
        cat: 'b',
      },
      {
        id: 14,
        name: "Nike Red High Tops",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/QcvzydB/nikes-red.png",
        price: 160,
        cat: 'b',
      },
      {
        id: 15,
        name: "Nike Brown High Tops",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/fMTV342/nike-brown.png",
        price: 160,
        cat: 'b',
      },
      {
        id: 16,
        name: "Air Jordan Limited",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
        price: 190,
        cat: 'b',
      },
      {
        id: 17,
        name: "Timberlands",
        date: '15-16.09.2020',
        imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
        price: 200,
        cat: 'b',
      },
    ],
  },
};

export default SHOP_DATA;
